apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: default
spec:
  # Here we can limit the types of resources we allow
  # users to create via this project
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Limit the destination cluster and namespace
  # E.g. we can have a project which only allows
  # "deployments" to a dev cluster in some namespace
  destinations:
  - namespace: '*'
    server: '*'
  # Here we can limit the source repos for our project
  # In this case we are only allowing the Helm Stable repo
  sourceRepos:
  - '*'
